import type { Employee } from "@canvas/core";

export const sampleCompany: Employee[] = [
  {
    id: "ceo",
    name: "Ada Lovelace",
    title: "CEO",
    managerId: null,
    department: "operations",
    meta: { role: "executive" },
  },
  {
    id: "cto",
    name: "Grace Hopper",
    title: "CTO",
    managerId: "ceo",
    department: "engineering",
    meta: { role: "executive" },
  },
  {
    id: "cpo",
    name: "Alan Turing",
    title: "CPO",
    managerId: "ceo",
    department: "product",
    meta: { role: "executive" },
  },
  {
    id: "cfo",
    name: "Katherine Johnson",
    title: "CFO",
    managerId: "ceo",
    department: "finance",
    meta: { role: "executive" },
  },
  {
    id: "vp-eng-platform",
    name: "Barbara Liskov",
    title: "VP Platform",
    managerId: "cto",
    department: "engineering",
  },
  {
    id: "vp-eng-product",
    name: "Margaret Hamilton",
    title: "VP Product Eng",
    managerId: "cto",
    department: "engineering",
  },
  {
    id: "vp-design",
    name: "Susan Kare",
    title: "VP Design",
    managerId: "cpo",
    department: "design",
  },
  {
    id: "sr-eng-1",
    name: "Linus Torvalds",
    title: "Staff Engineer",
    managerId: "vp-eng-platform",
    department: "engineering",
  },
  {
    id: "sr-eng-2",
    name: "Guido van Rossum",
    title: "Staff Engineer",
    managerId: "vp-eng-platform",
    department: "engineering",
    dottedLineManagerIds: ["vp-eng-product"],
  },
  {
    id: "eng-3",
    name: "Junior Engineer",
    title: "Software Engineer",
    managerId: "vp-eng-product",
    department: "engineering",
  },
  {
    id: "des-1",
    name: "Ellen Ullman",
    title: "Senior Designer",
    managerId: "vp-design",
    department: "design",
  },
  {
    id: "vacant-1",
    name: "Open Role",
    title: "Head of Growth",
    managerId: "ceo",
    department: "marketing",
    meta: { role: "vacant", title: "Head of Growth" },
  },
];
