import type { Employee } from "@canvas/core";

export const sampleCompany: Employee[] = [
  {
    id: "ceo",
    name: "Ada Lovelace",
    title: "CEO",
    managerId: null,
    department: "operations",
    email: "ada@example.com",
    location: "London",
    tenureYears: 12,
    employmentType: "employee",
    workMode: "hybrid",
    meta: { role: "executive" },
  },
  {
    id: "cto",
    name: "Grace Hopper",
    title: "CTO",
    managerId: "ceo",
    department: "engineering",
    email: "grace@example.com",
    location: "Remote",
    tenureYears: 8,
    employmentType: "employee",
    workMode: "remote",
    meta: { role: "executive" },
  },
  {
    id: "cpo",
    name: "Alan Turing",
    title: "CPO",
    managerId: "ceo",
    department: "product",
    email: "alan@example.com",
    location: "Cambridge",
    tenureYears: 6,
    employmentType: "employee",
    workMode: "onsite",
    meta: { role: "executive" },
  },
  {
    id: "cfo",
    name: "Katherine Johnson",
    title: "CFO",
    managerId: "ceo",
    department: "finance",
    email: "katherine@example.com",
    location: "Virginia",
    tenureYears: 10,
    employmentType: "employee",
    workMode: "hybrid",
    meta: { role: "executive" },
  },
  {
    id: "vp-eng-platform",
    name: "Barbara Liskov",
    title: "VP Platform",
    managerId: "cto",
    department: "engineering",
    email: "barbara@example.com",
    location: "Boston",
    tenureYears: 5,
    employmentType: "employee",
    workMode: "hybrid",
  },
  {
    id: "vp-eng-product",
    name: "Margaret Hamilton",
    title: "VP Product Eng",
    managerId: "cto",
    department: "engineering",
    email: "margaret@example.com",
    location: "Cambridge, MA",
    tenureYears: 7,
    employmentType: "employee",
    workMode: "onsite",
  },
  {
    id: "vp-design",
    name: "Susan Kare",
    title: "VP Design",
    managerId: "cpo",
    department: "design",
    email: "susan@example.com",
    location: "San Francisco",
    tenureYears: 4,
    employmentType: "employee",
    workMode: "remote",
  },
  {
    id: "sr-eng-1",
    name: "Linus Torvalds",
    title: "Staff Engineer",
    managerId: "vp-eng-platform",
    department: "engineering",
    email: "linus@example.com",
    location: "Portland",
    tenureYears: 3,
    employmentType: "employee",
    workMode: "remote",
  },
  {
    id: "sr-eng-2",
    name: "Guido van Rossum",
    title: "Staff Engineer",
    managerId: "vp-eng-platform",
    department: "engineering",
    email: "guido@example.com",
    location: "Amsterdam",
    tenureYears: 2,
    employmentType: "contractor",
    workMode: "hybrid",
    dottedLineManagerIds: ["vp-eng-product"],
  },
  {
    id: "eng-3",
    name: "Junior Engineer",
    title: "Software Engineer",
    managerId: "vp-eng-product",
    department: "engineering",
    email: "junior@example.com",
    location: "New York",
    tenureYears: 1,
    employmentType: "intern",
    workMode: "onsite",
  },
  {
    id: "des-1",
    name: "Ellen Ullman",
    title: "Senior Designer",
    managerId: "vp-design",
    department: "design",
    email: "ellen@example.com",
    location: "Remote",
    tenureYears: 3,
    employmentType: "employee",
    workMode: "remote",
  },
  {
    id: "vacant-1",
    name: "Open Role",
    title: "Head of Growth",
    managerId: "ceo",
    department: "marketing",
    meta: { role: "vacant", title: "Head of Growth" },
  },
];
